import { defineField, defineType } from 'sanity'

export const platformType = defineType({
  name: 'platform',
  title: 'Platforme',
  type: 'document',
  groups: [
    { name: 'general', title: 'Generelt' },
    { name: 'details', title: 'Detaljer' },
    { name: 'review', title: 'Anmeldelse' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Navn',
      type: 'string',
      group: 'general',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'general',
      options: { source: 'name' },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'logo',
      title: 'Logo',
      type: 'image',
      group: 'general',
      options: { hotspot: true },
    }),
    defineField({
      name: 'affiliateUrl',
      title: 'Affiliate link',
      type: 'url',
      group: 'general',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'rating',
      title: 'Vurdering (0-10)',
      type: 'number',
      group: 'general',
      validation: (r) => r.min(0).max(10),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Kort beskrivelse',
      type: 'text',
      rows: 2,
      group: 'general',
    }),
    defineField({
      name: 'badges',
      title: 'Badges',
      type: 'array',
      group: 'general',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'fx: Mest populær, Ny platform',
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sorteringsrækkefølge',
      type: 'number',
      group: 'general',
      description: 'Lavere tal = højere placering',
      initialValue: 99,
    }),
    defineField({
      name: 'minDeposit',
      title: 'Minimum indbetaling',
      type: 'string',
      group: 'details',
    }),
    defineField({
      name: 'fees',
      title: 'Gebyrer',
      type: 'string',
      group: 'details',
    }),
    defineField({
      name: 'withdrawalSpeed',
      title: 'Udbetalingstid',
      type: 'string',
      group: 'details',
    }),
    defineField({
      name: 'blockchain',
      title: 'Blockchain',
      type: 'string',
      group: 'details',
      description: 'fx: Polygon, Ethereum',
    }),
    defineField({
      name: 'foundedYear',
      title: 'Grundlagt år',
      type: 'number',
      group: 'details',
    }),
    defineField({
      name: 'markets',
      title: 'Tilgængelige markeder',
      type: 'array',
      group: 'details',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Politik', value: 'politics' },
          { title: 'Sport', value: 'sports' },
          { title: 'Crypto', value: 'crypto' },
          { title: 'Økonomi', value: 'economics' },
          { title: 'Underholdning', value: 'entertainment' },
          { title: 'Videnskab', value: 'science' },
        ],
        layout: 'grid',
      },
    }),
    defineField({
      name: 'pros',
      title: 'Fordele',
      type: 'array',
      group: 'review',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'cons',
      title: 'Ulemper',
      type: 'array',
      group: 'review',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'reviewBody',
      title: 'Fuld anmeldelse',
      type: 'array',
      group: 'review',
      of: [{ type: 'block' }],
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'rating', media: 'logo' },
    prepare({ title, subtitle, media }) {
      return { title, subtitle: subtitle ? `Vurdering: ${subtitle}/10` : '', media }
    },
  },
})
